Samedis-care/react-components

src/standalone/UIKit/SubActionButton.tsx
src/standalone/UIKit/index.ts
src/stories/standalone/UIKit/SubActionButton.story.tsx
src/stories/standalone/UIKit/index.story.ts

implementation SubActionButton

---

src/standalone/Selector/MultiSelectWithCheckBox.tsx
src/standalone/Selector/TypesMultiSelect.ts
src/standalone/Selector/index.ts
src/stories/standalone/Selector/MultiWithCheckBox.story.tsx
src/stories/standalone/Selector/index.story.ts

https://github.com/Components-care/backlog/issues/14

CC-14: Implemented selector checkbox control

---

src/standalone/UIKit/ActionButton.tsx
src/standalone/UIKit/FormButtons.tsx
src/standalone/UIKit/index.ts
src/stories/standalone/UIKit/FormButtons.story.tsx
src/stories/standalone/UIKit/index.story.ts

https://github.com/Components-care/backlog/issues/16

CC-16: Component with story for Form Buttons

---

package-lock.json
src/standalone/UIKit/Checkbox.tsx
src/standalone/UIKit/ComponentWithLabel.tsx
src/stories/standalone/UIKit/Checkbox.story.tsx
src/stories/standalone/UIKit/ComponentWithLabel.story.tsx
src/stories/standalone/UIKit/index.story.ts
test/__snapshots__/Storyshots.test.ts.snap

https://github.com/Components-care/backlog/issues/23

new styled checkbox control

---

src/standalone/UIKit/SubActionButton.tsx
test/__snapshots__/Storyshots.test.ts.snap

- only change text color on hover in full mode
- inverted colors in small mode

toned down hover effect

---

src/standalone/Selector/MultiSelectWithTags.tsx
src/stories/standalone/Selector/MultiWithTags.story.tsx
test/__snapshots__/Storyshots.test.ts.snap

https://github.com/Components-care/backlog/issues/19
- Added knob(`Enable Switch`) on story to enable/disable switch on multi select with tags component

CC-19: Added switch control on multiselect with tags component

---

src/assets/i18n/en/translation.json
src/non-standalone/Dialog/Utils.tsx
src/standalone/Selector/MultiSelectWithTags.tsx
src/standalone/UIKit/InputControls/DateInput.tsx
src/standalone/UIKit/InputControls/DateTimeInput.tsx
src/standalone/UIKit/TextFieldWithHelp.tsx
src/stories/standalone/Selector/MultiWithTags.story.tsx
src/stories/standalone/UIKit/InputControls/CurrencyInput.story.tsx
src/stories/standalone/UIKit/InputControls/DateInput.story.tsx
src/stories/standalone/UIKit/InputControls/DateTimeInput.story.tsx
src/stories/standalone/UIKit/InputControls/DecimalInputField.story.tsx
src/stories/standalone/UIKit/InputControls/IntegerInputField.story.tsx
src/stories/standalone/UIKit/TextFieldWithHelp.story.tsx
src/utils/useInputCursorFix.ts
test/Storyshots.test.ts

https://github.com/Components-care/backlog/issues/34

CC-34: Changes for info icon event to open a dialog to show info text

---

src/standalone/SignaturePad/index.tsx
src/stories/standalone/SignaturePad/SignaturePad.story.tsx

https://github.com/Components-care/backlog/issues/13
- Changes for supporting dark theme.
- Change info icon event to open a dialog to show info text.

CC-13: Changes for signature control

---

src/standalone/Selector/BaseSelector.tsx

(https://github.com/Components-care/backlog/issues/40)
- Handle loading flag to prevent infinite label

CC-40 Changes for preventing infinite loading label

---

src/standalone/Selector/BaseSelector.tsx

(https://github.com/Components-care/backlog/issues/49)
- Added attribute blurOnSelect in autocomplete

CC-49 Changes for selector unfocus after selection

---

src/backend-integration/Model/Types/Renderers/RendererSignature.tsx
src/non-standalone/Dialog/SignPadDialog.tsx
src/non-standalone/Dialog/Types.ts
src/non-standalone/SignaturePad/SignaturePad.tsx
src/standalone/SignPad/index.tsx
src/stories/non-standalone/SignaturePad/SignaturePad.story.tsx

- Add height-width in story.
- Make sign pad height-width inherit.
- Remove position: fixed for sign text.

CC-62 Changes for signature control UI fixes

---

src/standalone/Selector/BaseSelector.tsx

resolves (https://github.com/Components-care/backlog/issues/60)
- Added selectOnFocus attribute on Autocomplete

CC-60 Changes for prevent text selection if disable search is enabled

---

src/standalone/FileUpload/Generic/index.tsx
src/standalone/FileUpload/Image/ImageSelector.tsx
src/standalone/GroupBox/index.tsx
src/stories/standalone/FileUpload/FileUpload.story.tsx
src/stories/standalone/FileUpload/ImageSelector.story.tsx
src/stories/standalone/GroupBox/GroupBox.story.tsx

(https://github.com/Components-care/backlog/issues/64)
- Add smallLabel knobs to stories where group box is used
- Render InputLabel if smallLabel is truthy

CC-64 Changes for rendering InputLabel if smallLabel is truthy

---

src/backend-integration/Model/Types/Renderers/UIKit/RendererDateNullable.tsx
src/standalone/Selector/MultiSelectWithoutGroup.tsx
src/standalone/UIKit/InputControls/DateInput.tsx
src/standalone/UIKit/TextFieldWithHelp.tsx
src/stories/standalone/UIKit/InputControls/DateInput.story.tsx

(https://github.com/Components-care/backlog/issues/65)
- Add TextField with endAdornment for openInfo and open calender
- Support keyboard input 
- Show error for invalid date

CC-65 UIKit Date Inputs: Support entering dates via keyboard

---

src/assets/i18n/de/translation.json
src/assets/i18n/en/translation.json
src/assets/i18n/fr/translation.json
src/assets/i18n/ru/translation.json
src/assets/i18n/uz/translation.json
src/standalone/Selector/BaseSelector.tsx
src/standalone/Selector/MultiSelectWithTags.tsx
src/standalone/Selector/MultiSelectWithoutGroup.tsx
src/stories/standalone/Selector/Multi.story.tsx
src/stories/standalone/Selector/MultiWithTags.story.tsx
src/stories/standalone/Selector/MultiWithoutGroup.story.tsx
src/stories/standalone/Selector/Single.story.tsx

[CC-78](https://github.com/Components-care/backlog/issues/78)

 Changes for missing translations in selector

---

src/standalone/InlineSwitch/index.tsx
src/standalone/Selector/MultiSelectWithTags.tsx
src/standalone/Selector/MultiSelectWithoutGroup.tsx
test/standalone/Selector/__snapshots__/index.story.storyshot

ref for suggested UI changes: https://github.com/TQsoft-GmbH/samed-care-backlog/issues/1#issuecomment-814680828

CC-81: UI fixes for Switch control in MultiSelectWithTag

---

src/assets/i18n/de/translation.json
src/assets/i18n/en/translation.json
src/assets/i18n/fr/translation.json
src/assets/i18n/ru/translation.json
src/assets/i18n/uz/translation.json

Fixes https://github.com/Components-care/backlog/issues/87

updated translations

---

src/assets/i18n/de/translation.json
src/assets/i18n/en/translation.json
src/assets/i18n/fr/translation.json
src/assets/i18n/ru/translation.json
src/assets/i18n/uz/translation.json

Fixes https://github.com/Components-care/backlog/issues/88

updated filter

---

src/backend-components/DataGrid/index.tsx
src/backend-components/Selector/BackendMultiSelect.tsx
src/backend-components/Selector/BackendSingleSelect.tsx
src/framework/MuiPickerUtils.tsx
src/non-standalone/Dialog/SignPadDialog.tsx
src/standalone/DataGrid/Content/ColumnHeaderContent.tsx
src/standalone/DataGrid/Content/FilterEntry.tsx
src/standalone/DataGrid/Content/index.tsx
src/standalone/DataGrid/CustomFilterDialog/FilterDialog.tsx
src/standalone/DataGrid/Footer/DataActionBarView.tsx
src/standalone/DataGrid/Footer/PaginationView.tsx
src/standalone/DataGrid/Header/ActionBarView.tsx
src/standalone/DataGrid/Header/CustomFiltersButton.tsx
src/standalone/DataGrid/Settings/SettingsDialog.tsx
src/standalone/FileUpload/Generic/index.tsx
src/standalone/FileUpload/Image/ImageSelector.tsx
src/standalone/HowToBox/index.tsx
src/standalone/LocalizedDateTimePickers/LocalizedDatePicker.tsx
src/standalone/LocalizedDateTimePickers/LocalizedDateTimePicker.tsx
src/standalone/LocalizedDateTimePickers/LocalizedKeyboardDatePicker.tsx
src/standalone/Schedule/Scrollable/ScrollableScheduleWeek.tsx
src/standalone/Schedule/Weekly/index.tsx
src/standalone/Selector/BaseSelector.tsx
src/standalone/Selector/MultiSelectWithoutGroup.tsx
src/standalone/SignPad/index.tsx
src/standalone/UIKit/InputControls/CurrencyInput.tsx
src/standalone/UIKit/InputControls/DecimalInputField.tsx
src/standalone/UIKit/InputControls/IntegerInputField.tsx
src/standalone/UIKit/NumberFormatter.tsx

resolves  Components-care/backlog/issues/90

CC-90: Refactor usage of useTranlation with useCCTranslations

---

src/standalone/DataGrid/Content/Cell.tsx
src/standalone/DataGrid/Content/ColumnHeader.tsx
src/standalone/DataGrid/Content/ColumnHeaderContent.tsx
src/standalone/FileUpload/Generic/File.tsx
src/standalone/FileUpload/Generic/index.tsx
src/standalone/Portal/CollapsibleMenu.tsx
src/standalone/Portal/Menu/index.tsx
src/standalone/Portal/MenuItem/JumboReact/Dark/index.tsx
src/standalone/Portal/MenuItem/JumboReact/Light/index.tsx
src/standalone/Schedule/Common/DayContents.tsx
src/standalone/Schedule/Scrollable/index.tsx
src/standalone/Selector/MultiSelectEntry.tsx
test/standalone/Portal/__snapshots__/index.story.storyshot

resolves https://github.com/Components-care/backlog/issues/89

CC-89: Used combine class name utils

---

src/standalone/Icons/SuccessOutlinedIcon.tsx
src/standalone/InfoBox/index.tsx
src/stories/standalone/InfoBox/InfoBox.story.tsx
test/standalone/InfoBox/__snapshots__/index.story.storyshot

resolves https://github.com/Components-care/backlog/issues/92

CC-92: Enhanced InfoBox component by adding status parameter

---

src/standalone/InfoBox/index.tsx

- Line break fixes for infobox message.

Updated UI for InfoBox

---

src/assets/i18n/de/translation.json
src/assets/i18n/fr/translation.json
src/assets/i18n/ru/translation.json
src/assets/i18n/uz/translation.json

Fixes https://github.com/Components-care/backlog/issues/93

translations

---

src/backend-integration/Model/Types/Renderers/Material-UI/RendererDate.tsx
src/backend-integration/Model/Types/Renderers/Material-UI/RendererDateNullable.tsx
src/backend-integration/Model/Types/Renderers/UIKit/RendererDateNullable.tsx
src/backend-integration/Model/Types/Renderers/UIKit/RendererDateTimeNullable.tsx

- resolves https://github.com/Components-care/backlog/issues/95

CC-95: Added missing prop to check visibility.required flag on Date and DateTime component

---

src/standalone/UIKit/TextFieldWithHelp.tsx
src/utils/index.ts
src/utils/isTouchDevice.ts
test/standalone/UIKit/InputControls/__snapshots__/index.story.storyshot
test/standalone/UIKit/__snapshots__/index.story.storyshot

resolves https://github.com/Components-care/backlog/issues/94
@vishesh-ats please test

[CC-94] Add clear button to TextFieldWithHelp on touch devices

---

src/backend-components/DataGrid/index.tsx
src/backend-components/Selector/CrudMultiSelect.tsx
src/backend-components/Selector/CrudMultiSelectWithGroups.tsx
src/backend-components/Selector/useCrudSelect.ts
src/standalone/DataGrid/Header/ExportMenuEntry.tsx

and various typescript fixes/improvements

CRUD Select API

---

src/standalone/Selector/BaseSelector.tsx
src/standalone/Selector/MultiSelectEntry.tsx

- resolves https://github.com/Components-care/backlog/issues/96

CC-96: Add the new prop to make the selector entry ignored 

---

src/i18n.ts

- Add currencies for the i18n file

Fixes for currencies into i18n
